name: Dev PR
on:
  # Triggers the workflow on push of any branches except main and preprod
  pull_request:
    branches: ["preprod"]
jobs:
  Release-Created:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I'm a dev writing a policy"
